### ISSUE TITLE
Debug command doesn't work well with arrays

### ISSUE THREAD

**Issue by lskupnjak** [SofaScore/purgatory#45]
**Describe the bug**

```
     * @Rest\Get("/{id}/{type}")
     * @PurgeOn(Entity::class,
     *     properties={"prop1", "prop2"},
     *     parameters={"id": "id", "type": {"@value1","@value2"}}
     * )
```

Then run `bin/console purgatory:debug Entity::prop1`.

Expected:
Two urls get dumped:

```
        route_name
                path: {id}/{type}
                parameters: 
                        id: id
                        type: @value1

        route_name
                path: {id}/{type}
                parameters: 
                        id: id
                        type: @value2
```

What happens:
One url get dumped:

```
        route_name
                path: {id}/{type}
                parameters: 
                        id: id
                        type: @value1
```

**Additional context**
Looks like `\SofaScore\Purgatory\Command\DebugCommand::dumpMappingValueArrayElement` has u bug where only `value[0]` is dumped, and not all values inside of that array.
